### ISSUE TITLE
Update the component to use core components instead of add-ons

### ISSUE THREAD

**Issue by juuso-vaadin** [vaadin-component-factory/lookup-field-flow#11]
~~In Vaadin 23.2 new Vaadin Multi Select Combo Box is available. It should replace the multiselect-combo-box add-on in the lookupfield.~~ Done already 👍 

In addition the Vaadin Dialog nowadays contains header and footer areas and should replace vcf-enhanced-dialog add-on.

**Comment by jcgueriaud1** [comment]
It seems to be done in the latest version (v24)
