### ISSUE TITLE
 Cannot read properties of undefined (reading 'assignedNodes') in custom filter view

### ISSUE THREAD

**Issue by jcgueriaud1** [vaadin-component-factory/lookup-field-flow#17]
The pages in the demo app are not working:
http://localhost:8080/custom-filter-type
and
http://localhost:8080/custom-filter

There is a javascript error:
 Cannot read properties of undefined (reading 'assignedNodes')

**Comment by jcgueriaud1** [comment]
![image](https://user-images.githubusercontent.com/51313578/230347329-2b4b9415-309e-4fd4-a68c-e52b1eb00c39.png)

**Comment by brunovianarezende** [comment]
https://github.com/vaadin-component-factory/vcf-lookup-field/pull/7

**Comment by bwajtr** [comment]
I've reviewed and tested the PR - all seems OK. Merged

**Comment by bwajtr** [comment]
Fixed in web-component release 23.3.1
included in Flow component version 23.3.5
