### ISSUE TITLE
Required indicator is not shown

### ISSUE THREAD

**Issue by juuso-vaadin** [vaadin-component-factory/lookup-field-flow#19]
Lookup Field has `setRequiredIndicatorVisible()` method available, but it has no effect.

Expected behavior is as in Combo Box

> Required fields are marked with an indicator next to the label, and become invalid if left empty after having been focused.

Invalid state can be rendered and error message works as expected.

**Comment by bwajtr** [comment]
Fixed in release 23.3.5
